=== lepfhty/data-explorer/src/main/resources/mapping.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://vpicu.chla.usc.edu/explorer/mapping"
xmlns:map="http://vpicu.chla.usc.edu/explorer/mapping"
elementFormDefault="qualified">

  <complexType name="GenericNamedType" abstract="true">
    <attribute name="name" type="token"/>
    <attribute name="description" type="token"/>
  </complexType>
  
  <complexType name="DeclarationType" abstract="true">
    <complexContent>
      <extension base="map:GenericNamedType">
        <attribute name="id" type="ID" use="required"/>
      </extension>
    </complexContent>
  </complexType>
  
  <complexType name="ReferenceType" abstract="true">
    <complexContent>
      <extension base="map:GenericNamedType">
        <attribute name="ref" type="IDREF" use="required"/>
      </extension>
    </complexContent>
  </complexType>
  
  <complexType name="SourceType" abstract="true">
    <complexContent>
      <extension base="map:DeclarationType">
        <attribute name="url" type="anyURI" use="required"/>
      </extension>
    </complexContent>
  </complexType>
  
  <complexType name="DBSourceType">
    <complexContent>
      <extension base="map:SourceType"/>
    </complexContent>
  </complexType>
  
  <complexType name="CSVSourceType">
    <complexContent>
      <extension base="map:SourceType">
        <attribute name="headers" type="NMTOKENS"/>
      </extension>
    </complexContent>
  </complexType>
  
  <complexType name="SourcesType">
    <choice minOccurs="1" maxOccurs="unbounded">
      <element name="dbsource" type="map:DBSourceType"/>
      <element name="csvsource" type="map:CSVSourceType"/>
    </choice>
  </complexType>
  
  <complexType name="ValueFunctionType">
    <simpleContent>
      <extension base="string">
        <attribute name="language" use="required">
          <simpleType>
            <restriction base="NMTOKEN">
              <enumeration value="javascript"/>
            </restriction>
          </simpleType>
        </attribute>
      </extension>
    </simpleContent>
  </complexType>
  
  <complexType name="SourceMappingType" abstract="true">
    <complexContent>
      <extension base="map:ReferenceType">
        <sequence>
          <element name="value-function" type="map:ValueFunctionType" minOccurs="0" maxOccurs="1"/>
        </sequence>
        <attribute name="idcol" type="NMTOKEN"/>
        <attribute name="idval" type="string"/>
        <attribute name="valcol" type="NMTOKEN" use="required"/>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="DBSourceMappingType">
    <complexContent>
      <extension base="map:SourceMappingType">
        <attribute name="schema" type="NMTOKEN"/>
        <attribute name="table" type="NMTOKEN"/>
      </extension>
    </complexContent>
  </complexType>
  
  <complexType name="CSVSourceMappingType">
    <complexContent>
      <extension base="map:SourceMappingType"/>
    </complexContent>
  </complexType>
  
  <complexType name="VariableType">
    <complexContent>
      <extension base="map:GenericNamedType">
        <choice minOccurs="1" maxOccurs="unbounded">
          <element name="dbsource" type="map:DBSourceMappingType"/>
          <element name="csvsource" type="map:CSVSourceMappingType"/>
        </choice>
        <attribute name="dataset-id" type="NMTOKEN" use="required"/>
      </extension>
    </complexContent>
  </complexType>
  
  <complexType name="DatasetType">
    <complexContent>
      <extension base="map:GenericNamedType">
        <sequence>
          <element name="variable" type="map:VariableType" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  
  <complexType name="MapsType">
    <sequence>
      <element name="sources" type="map:SourcesType" minOccurs="1" maxOccurs="1"/>
      <element name="dataset" type="map:DatasetType" minOccurs="1" maxOccurs="unbounded">
        <unique name="uniqueVariableInDataset">
          <selector xpath="map:variable"/>
          <field xpath="@dataset-id"/>
        </unique>
      </element>
    </sequence>
  </complexType>
  
  <element name="maps" type="map:MapsType"/>

</schema>

=== lepfhty/data-explorer/src/main/resources/mapping.xml
<maps xmlns="http://vpicu.chla.usc.edu/mapping"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://vpicu.chla.usc.edu/explorer/mapping mapping.xsd">
  <sources>
    <dbsource id="cerner" url="jdbc:jtds:sqlserver://hostname:1433/DBNAME;instance=INSTANCE"
              name="Cerner" description="Cerner KIDS EHR mirror"/>
    <dbsource id="ismnew" url="jdbc:oracle:thin:@127.0.0.1:1521:ORCL"
              name="ISM New" description="Phillips CareVue Flowsheets, ISM New"/>
    <csvsource id="cedars-flowsheet" url="file://cedars/flowsheet.csv" headers="asdf foo var hello world goodbye"
               name="Cedars-Sinai Flowsheet" description="A flowsheet CSV file provided by Cedars-Sinai Hospital"/>
  </sources>
  <dataset name="VPS PRISM3 Dataset" description="variables for the VPS PRISM3 metric">
    <variable dataset-id="1" name="Systolic Blood Pressure" description="a non-invasive systolic blood pressure in mmHg">
      <dbsource ref="cerner"
                schema="dbo"
                table="clinical_event"
                idcol="event_cd"
                idval="688367"
                valcol="result_val"/>
      <dbsource ref="ismnew"
                schema="ism"
                table="chartevents"
                idcol="itemid"
                idval="764"
                valcol="value1"/>
      <csvsource ref="cedars-flowsheet"
                 idcol="id"
                 idval="123"
                 valcol="result">
                 <value-function language="javascript">
                   valcol.split('/')[0]
                 </value-function>
      </csvsource>
    </variable>
    <variable dataset-id="2" >
      <dbsource ref="ismnew" valcol="value1"/>
    </variable>
  </dataset>
</maps>
